#!/usr/bin/env python3
"""Sector Chakra icon: the four RRG quadrants as a wheel turning clockwise.

One geometry, three outputs, so they can't disagree:
  out/ic_launcher_foreground.xml   Android adaptive-icon foreground (vector)
  out/ic_launcher_monochrome.xml   Android 13+ themed icon (single colour)
  out/icon-512.png                 Play Store icon (full square, Play masks it)
  out/preview.png                  how it looks under common launcher masks
Usage: chakra_icon.py <outdir>
"""
import math, os, sys
from PIL import Image, ImageDraw

OUT = sys.argv[1] if len(sys.argv) > 1 else "out"
os.makedirs(OUT, exist_ok=True)

# Adaptive icon canvas: 108x108dp, anything outside the central 66dp circle
# (radius 33) may be cropped by the launcher mask.
C = 54.0
R_OUT, R_IN = 30.5, 21.5            # ring
FLARE = 3.2                          # arrowhead pokes this far past the ring
GAP = 9.0                            # degrees between quadrants
ARROW = 13.0                         # degrees taken by each arrowhead
HUB = 7.0
SPOKES = os.environ.get("SPOKES") == "1"   # optional: 4 spokes on the RRG axes (tried; reads as a crosshair)
AXIS_W = 2.2
AXIS_COL = "#8B8A83"
BG = "#141517"
ACCENT = "#E8B84A"
# RRG order, clockwise from 12 o'clock: Leading (top-right) -> Weakening
# (bottom-right) -> Lagging (bottom-left) -> Improving (top-left).
QUADS = [(-90, "#3EC46F"), (0, "#D8B53C"), (90, "#D4564A"), (180, "#4D84E2")]


def pt(r, deg):
    a = math.radians(deg)
    return (C + r * math.cos(a), C + r * math.sin(a))


def quad_shape(start):
    """Annular arc + clockwise arrowhead, as (vector path, polygon points)."""
    a0 = start + GAP / 2                 # arc starts
    a1 = start + 90 - GAP / 2 - ARROW    # arc body ends, arrowhead begins
    tip = start + 90 - GAP / 2           # arrow tip
    mid = (R_OUT + R_IN) / 2
    o0, o1 = pt(R_OUT, a0), pt(R_OUT, a1)
    i0, i1 = pt(R_IN, a0), pt(R_IN, a1)
    fo, fi, t = pt(R_OUT + FLARE, a1), pt(R_IN - FLARE, a1), pt(mid, tip)
    f = lambda p: f"{p[0]:.2f},{p[1]:.2f}"
    path = (f"M{f(o0)} A{R_OUT},{R_OUT} 0 0 1 {f(o1)} L{f(fo)} L{f(t)} L{f(fi)} "
            f"L{f(i1)} A{R_IN},{R_IN} 0 0 0 {f(i0)} Z")
    poly = [pt(R_OUT, a0 + (a1 - a0) * k / 40) for k in range(41)]
    poly += [fo, t, fi]
    poly += [pt(R_IN, a1 - (a1 - a0) * k / 40) for k in range(41)]
    return path, poly


shapes = [(quad_shape(s), col) for s, col in QUADS]


def vector(colour_of):
    h, w2 = R_IN - 2.5, AXIS_W / 2          # spokes: hub to the inner rim only
    axes = (f'    <path android:fillColor="{colour_of(AXIS_COL)}" android:pathData="'
            f'M{C - w2},{C - h} h{AXIS_W} v{2 * h} h{-AXIS_W} Z '
            f'M{C - h},{C - w2} v{AXIS_W} h{2 * h} v{-AXIS_W} Z" />\n')
    body = (axes if SPOKES else "") + "\n".join(f'    <path android:fillColor="{colour_of(col)}" android:pathData="{p}" />'
                     for (p, _), col in shapes)
    hub = (f'    <path android:fillColor="{colour_of(ACCENT)}" android:pathData="'
           f'M{C - HUB},{C} a{HUB},{HUB} 0 1 0 {2 * HUB},0 a{HUB},{HUB} 0 1 0 {-2 * HUB},0 Z" />')
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Sector Chakra: the four RRG quadrants turning clockwise\n'
            '     (Leading, Weakening, Lagging, Improving) around an amber hub.\n'
            '     Generated by chakra_icon.py - edit the script, not this file. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android" '
            'android:width="108dp" android:height="108dp" '
            'android:viewportWidth="108" android:viewportHeight="108">\n'
            f'{body}\n{hub}\n</vector>\n')


open(f"{OUT}/ic_launcher_foreground.xml", "w").write(vector(lambda c: c))
open(f"{OUT}/ic_launcher_monochrome.xml", "w").write(vector(lambda c: "#FFFFFF"))


def render(size, mask=None, bg=BG):
    """Raster render at `size` px, supersampled 4x. mask: None|circle|squircle|rounded."""
    S = size * 4
    k = S / 108.0
    im = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.rectangle([0, 0, S, S], fill=bg)
    h, w2 = (R_IN - 2.5) * k, AXIS_W / 2 * k
    if SPOKES:
        d.rectangle([C * k - w2, C * k - h, C * k + w2, C * k + h], fill=AXIS_COL)
        d.rectangle([C * k - h, C * k - w2, C * k + h, C * k + w2], fill=AXIS_COL)
    for (_, poly), col in shapes:
        d.polygon([(x * k, y * k) for x, y in poly], fill=col)
    d.ellipse([(C - HUB) * k, (C - HUB) * k, (C + HUB) * k, (C + HUB) * k], fill=ACCENT)
    if mask:
        m = Image.new("L", (S, S), 0)
        md = ImageDraw.Draw(m)
        if mask == "circle":
            md.ellipse([0, 0, S, S], fill=255)
        elif mask == "rounded":
            md.rounded_rectangle([0, 0, S, S], S * 0.22, fill=255)
        else:  # squircle-ish
            md.rounded_rectangle([0, 0, S, S], S * 0.38, fill=255)
        im.putalpha(m)
    return im.resize((size, size), Image.LANCZOS)


# Play Store icon: full-bleed square; Play applies its own rounded mask.
# The adaptive canvas is 108dp but the visible part is the middle 72dp, so the
# store icon is cropped to that middle to match what the launcher shows.
big = render(768)
crop = int(768 * 18 / 108)
store = big.crop((crop, crop, 768 - crop, 768 - crop)).resize((512, 512), Image.LANCZOS).convert("RGB")
store.save(f"{OUT}/icon-512.png")

# Preview: the 72dp visible area under three launcher masks, plus themed + light bg
prev = Image.new("RGB", (4 * 220 + 50, 260), "#2a2c30")
for i, (mask, bg, mono) in enumerate([("circle", BG, False), ("squircle", BG, False),
                                      ("rounded", BG, False), ("circle", "#E8E6F0", True)]):
    tile = render(288, None, BG)          # always render on the dark bg, tint below
    c = int(288 * 18 / 108)
    tile = tile.crop((c, c, 288 - c, 288 - c)).resize((192, 192), Image.LANCZOS)
    if mono:  # themed-icon look: one tint on a pale background
        g = tile.convert("L").point(lambda v: 0 if v < 60 else 255)   # icon = bright
        tinted = Image.new("RGBA", tile.size, "#3B3A6B")
        base = Image.new("RGBA", tile.size, bg)
        tile = Image.composite(tinted, base, g)
    m = Image.new("L", (192, 192), 0)
    md = ImageDraw.Draw(m)
    {"circle": lambda: md.ellipse([0, 0, 192, 192], fill=255),
     "squircle": lambda: md.rounded_rectangle([0, 0, 192, 192], 72, fill=255),
     "rounded": lambda: md.rounded_rectangle([0, 0, 192, 192], 42, fill=255)}[mask]()
    prev.paste(tile.convert("RGB"), (20 + i * 230, 34), m)
prev.save(f"{OUT}/preview.png")
print("wrote", sorted(os.listdir(OUT)))
